<?php
/**
 * Created by PhpStorm.
 * User: aczietlow
 * Date: 1/25/15
 * Time: 4:12 PM
 */

namespace FlightSim\Entity;


abstract class Entity {
    /**
     * Load existing Destination Entities.
     *
     * @param String
     *   Unique identifier for the destination entity.
     *
     * @return mixed
     */
    abstract public function load($identifier);

    /**
     * Populates this object based on an incoming array generated by the
     * toArray() method above.
     *
     * @param $array
     */
    public function fromArray($array) {
        foreach($array as $key => $value) {
            if (property_exists($this, $key) && $key != 'debugData') {
                $this->{$key} = $value;
            }
        }
    }
} 